### ISSUE TITLE
timeout argument is not configured with type=int

### ISSUE THREAD

**Issue by guylando** [megadose/holehe#110]
In core.py maincore function

parser.add_argument("-T","--timeout", default=10, required=False,dest="timeout",
should be 
parser.add_argument("-T","--timeout", type=int, default=10, required=False,dest="timeout",

or otherwise the argument is considered a string and then "client = httpx.AsyncClient(timeout=timeout)" produces a client which fails on all requests.

**Comment by megadose** [comment]
https://github.com/megadose/holehe/commit/508e47ffe1d704315ebcca32b3ba1195fa44ac89
