### ISSUE TITLE
you cant download with git clone

### ISSUE THREAD

**Issue by L9gecko** [megadose/holehe#128]
![Screenshot_10](https://user-images.githubusercontent.com/122942804/215351542-55ce4f9b-3af0-4c25-bbe3-86295b4dd965.png)

**Comment by Oples** [comment]
Seems like a problem with your local git or Windows installation,
**git** was unable to create a directory in your folder `C:\Users\παναγιώτης\` **before** any attempt to download could be made.

So this is most likely **not** an issue with holohe but an issue with git or Windows, consider opening an issue at the respective sources: [git-scm](https://git-scm.com/community) and [Windows Comminity](https://answers.microsoft.com/it-it)

(Note: I'm **not** a Holehe developer but just a passerby)

**Comment by rekram1-node** [comment]
@L9gecko try cloning into a non root directory or run the command as administrator
