### ISSUE TITLE
command not found

### ISSUE THREAD

**Issue by ChosenAN** [megadose/holehe#129]
chosenxd-picoctf@webshell:~$ holehe test@gmail.com
-bash: holehe: command not found
already did pip3 install holehe

**Comment by rekram1-node** [comment]
Your PATH must be misconfigured, try something like:
echo "export PATH=\"`python3 -m site --user-base`/bin:\$PATH\"" >> ~/.bashrc
source ~/.bashrc

See: https://stackoverflow.com/questions/35898734/pip-installs-packages-successfully-but-executables-not-found-from-command-line for more details
