### ISSUE TITLE
Snapchat Does Not Work anymore, 405 error. 

### ISSUE THREAD

**Issue by davidwarshawsky** [megadose/holehe#132]
**Describe the bug**
Snapchat always provides an exception 405 code from the response.

**To Reproduce**
1. Clone the repo into your computer
2. Create a script from the readme and install relevant packages
3. Use an email you know has a snapchat account and attempt to run it on the email. 
4. Consistent 302 exception

**Expected behavior**
Expected to not get an error every time. 

**Desktop (please complete the following information):**
 - OS: mac 

**Additional context**

Request website needs to be changed to https://accounts.snapchat.com/accounts/login?continue=%2Faccounts%2Fwelcome

Then gets you to 405 error
Also, the snapchat.py file needs to have "import random" at the top. 
I also added this code for myself in snapchat.py after 
```req = await client.get("https://accounts.snapchat.com/accounts/login?continue=%2Faccounts%2Fwelcome")```
```
    if 'data-xsrf="' not in req.text or 'ata-web-client-id="' not in req.text:
        print("Snapchat throttled the request,try changing IP addresses")
        out.append({"name": name, "domain": domain, "method": method, "frequent_rate_limit": frequent_rate_limit,
                    "rateLimit": True,
                    "exists": False,
                    "emailrecovery": None,
                    "phoneNumber": None,
                    "others": None})
        return
```

**Comment by megadose** [comment]
Respond here please https://github.com/megadose/holehe/issues/124
