### ISSUE TITLE
Installing with command: python3 setup.py install

### ISSUE THREAD

**Issue by AnonymousPro5** [megadose/holehe#136]
When try to make installation with the last command: python3 setup.py install, a lot of error about version appears. (See attached picture).
Otherwise, I tried to install holehe making: pip install holehe. No errors found, but when I try to execute holehe command, "Not command found".
I try to found and import to the path, but nothing works.
![sdvsdv](https://user-images.githubusercontent.com/75625331/220867871-311f164f-068a-40f4-8713-c6a6480a1ea1.png)

**Comment by carouselcarousel** [comment]
I have the same problem

**Comment by saifrahmn** [comment]
Use py instead of python3 or pip
