### ISSUE TITLE
Application wide problem with rate limit 

### ISSUE THREAD

**Issue by 0x4x41** [megadose/holehe#147]
**Describe the bug**
It seems that almost every module will return rate limit true when anything unexpected happens instead of telling the user there was an error. This way many modules that have broken now always return ratelimit true even though they aren't actually rate limited. Proper checks for rate limits should be implemented instead of defaulting to it. This will make it much more clear as to what is happening and which modules need fixing instead of people changing their ip without results.

**Expected behavior**
The application only reports a module is rate limited when it actually is instead of when something goes wrong.

This is a rather large task to fix but it will result in quicker detection of broken modules and better feedback to the user.

**Comment by P3run** [comment]
It doesn't seem to be difficult. I can try to implement it.
