### ISSUE TITLE
Getting a Traceback

### ISSUE THREAD

**Issue by ronb65** [megadose/holehe#2]
Any idea why? stuck at 23% - 

Traceback (most recent call last):
  File "holehe.py", line 13, in <module>
    infos.append({str(website).split(" ")[1].split(" ")[0]:website(args.email)})
  File "C:\Users\X\Desktop\Python\holehe\holehe\core.py", line 150, in facebook
    return({"rateLimit":False,"exists":True,"emailrecovery":emailrecovery,"phoneNumber":phone,"others":{"FullName":full_name.text,"profilePicture":profile_picture}})
AttributeError: 'NoneType' object has no attribute 'text'

**Comment by megadose** [comment]
The problem comes from the module linked to facebook, did you try to simply relaunch ?

**Comment by megadose** [comment]
It's patch
