### ISSUE TITLE
I'm getting an error message whenever I trie to use holehe

### ISSUE THREAD

**Issue by guiinow** [megadose/holehe#21]
I've trie installing it with git clone and pip3 install, both of the methods, when I use: holehe example@email.com returns the following error: 

![image](https://user-images.githubusercontent.com/38408385/100560035-47bbbf80-3293-11eb-98bc-2c3663f7ce93.png)

**Comment by ZinahBaz** [comment]
Same here!

**Comment by megadose** [comment]
It's all right, it's fix !
Just restart holehe and the update will do it by itself.

**Comment by ddonnieddark0** [comment]
hi sorry for the newbie question. but how do i restart holehe?

**Comment by guiinow** [comment]
> hi sorry for the newbie question. but how do i restart holehe?

I had the same question. I guess I just closed and opened again. 
Make sure you've run git pull first. 
Best of luck.

**Comment by ddonnieddark0** [comment]
> > hi sorry for the newbie question. but how do i restart holehe?
> 
> I had the same question. I guess I just closed and opened again.
> Make sure you've run git pull first.
> Best of luck.

Hi. Tried git pull but doesn't work either. Any ideas?

**Comment by megadose** [comment]
When I say restart holehe it's just relaunche the command like :
holehe test@gmail.com 
because the updates are automatic.
