### ISSUE TITLE
Termux issue

### ISSUE THREAD

**Issue by doggukan** [megadose/holehe#35]
pip3 python 3.9 termux
the tool was working fine few weeks ago then i tried to install yesterday and it gives me this error

Unclosed <httpx.AsyncClient object at 0x7b97a4b2e0>. See https://www.python-httpx.org/async/#opening-and-closing-clients for details.

**Comment by megadose** [comment]
![termuxHolehe](https://user-images.githubusercontent.com/51822495/102127122-63ef5d00-3e4c-11eb-9a3f-3c82190f2356.png)
Normally it's good it's patch I've tested it works well.
