### ISSUE TITLE
Executable Claims to Check 112 Sites in ~13 Seconds, doesn't appear to actually *do* anything?

### ISSUE THREAD

**Issue by selllikesybok** [megadose/holehe#40]
In my limited tests, the various submodules for specific sites return the expected JSON (including correct identification of whether an account exists).

However, when running the standalone script with my personal gmail, I _always_ get a message like "112 sites checked in 13 seconds" (very impressive, of course).

The problem is that the report just as consistently states my gmail is not registered on any of those 112 sites. And most certainly is, on a few dozen of them.

Have I missed an essential step in setup, am I running it wrong, or what?

**Comment by megadose** [comment]
Could you give me the email address in question because it's not normal and I've never had this problem.

**Comment by megadose** [comment]
I sent you a message on twitter if it's the right mail it works very well for me, check that you have the latest version of holehe
