### ISSUE TITLE
Laredoute always appears as used

### ISSUE THREAD

**Issue by GritzTJ** [megadose/holehe#41]
Hello @megadose,

With my diferents test of this tool I noticed that holehe seems to always tell that a Laredoute account exists.

I tried to generate some random email addresses from https://www.mohmal.com and holehe returns everytime a positive answer for Laredoute.

Here is a random email address : 6066c24d85@firemailbox.club

Holehe version : 1.58.3.2
Python version : 3.6.8
OS version : CentOS 8

Thanks !

Edit : Tried to test this email address 2 times. First time the email address was associated with a Laredoute account for holehe. Second time it wasn't.

**Comment by megadose** [comment]
I removed the module, I tried to fix it but they patched the method.

**Comment by megadose** [comment]
Thank you very much for bringing this issue to my attention!
