### ISSUE TITLE
false positive with pinterest check

### ISSUE THREAD

**Issue by fastfire** [megadose/holehe#42]
Hi, after a few repeated attempts in a few minutes I verified that the check on pinterest always starts returning used for the account. Can you please check? Thank you very much!

**Comment by megadose** [comment]
I tested with tor without tor, with an old account and a recent one I have no problem, if you can send me a screenshot and the mail you had this problem with so that I can reproduce the problem it would be perfect.

**Comment by fastfire** [comment]
This is the output obtained after about 15 attempts with random email accounts (the previous did not show the false positive of Pinterest). The last account used was foo111188g84444kkh6k7s79ll@fooblabla334.it

[-] odnoklassniki
[-] office365
[-] onlinesequencer
[-] parler
[+] pinterest
[-] plurk
[-] pornhub
[-] protonmail
[-] raidforums
[-] rambler
[-] redtube
[-] replit
[-] rocketreach
[-] samsung
[-] seoclerks
[-] sevencups
[-] smule
[-] snapchat
[-] sporcle
[-] spotify
[-] strava
[-] taringa
[-] teamtreehouse
[-] tellonym
[-] thecardboard
[-] therianguide
[-] thevapingforum
[-] treasureclassifieds
[-] tumblr
[-] tunefind
[-] twitter
[x] venmo
[-] vivino
[-] voxmedia
[-] vrbo
[-] vsco
[-] wattpad
[-] wordpress
[-] xing
[-] xvideos
[x] yahoo

[+] Email used, [-] Email not used, [x] Rate limit
111 websites checked in 6.52 seconds

**Comment by megadose** [comment]
Very weird I threw holehe 20 times to sharpen but I have no false positive with this mail....
I still test with and without tor but it doesn't change anything...
Can you make the mistake again ? (if you run holehe again with the same mail you still have the error)

**Comment by fastfire** [comment]
Using a different ip (on a German cloud provider, before I used an Italian ip) the false positive is not generated.

**Comment by megadose** [comment]
Strange

**Comment by SimoneCagol** [comment]
I have the same problem!
