### ISSUE TITLE
Update regexPattern in modules/social_media/protonmail.py

### ISSUE THREAD

**Issue by pixelbubble** [megadose/holehe#43]
Hi,

I suggest you a new regexPattern "regexPattern3" in modules/social_media/protonmail.py:
- regexPattern1 = "2048:(.*)::" #RSA 2048-bit (Older but faster)
- regexPattern2 = "4096:(.*)::" #RSA 4096-bit (Secure but slow)
- regexPattern3 = "22::(.*)::" #X25519 (Modern, fastest, secure)
Source: https://protonmail.com/blog/elliptic-curve-cryptography/

You can test it with this API request: 
https://api.protonmail.ch/pks/lookup?op=index&search=thisisatestemailaccount@protonmail.com (elliptic curve system X25519)

**Comment by megadose** [comment]
Thank you very much it's done! https://github.com/megadose/holehe/commit/e61f25be071f689abe14b0e5d37ed5c90da6db22
