### ISSUE TITLE
FetLife alerts target email

### ISSUE THREAD

**Issue by StigP1337** [megadose/holehe#49]
FetLife ist sending an alert to the target email.

Alert mail content:

Having problems signing up to FetLife?
From: "FetLife" <KinkyOperator@fetlife.com>
To: ******@****.***
Date: 25.01.2021 13:45:47

We noticed that you were trying to signup to FetLife with *****@****.***.
The address is currently attached to your ******* profile and we can only
associate one account per email address.
If you are having problems logging into your ***** account you can reset your
password here:

Reset Password

P.S. if you weren't trying to signup to FetLife then we recommend you email
report@fetlife.com so we can look into it.

**Comment by megadose** [comment]
Very weird I had already done the test with different mail to me and none of them were alerted.
I've just re-tested 
![image](https://user-images.githubusercontent.com/51822495/105730232-65717200-5f2e-11eb-9fb2-ae07c15fd94e.png)
![image](https://user-images.githubusercontent.com/51822495/105730260-6e624380-5f2e-11eb-8c47-f2249b122213.png)
I remove the module just in case and I'll ask for more information
