### ISSUE TITLE
What does "others" mean?

### ISSUE THREAD

**Issue by johnnyblackday** [megadose/holehe#52]
Hello, 

I ran a search with an e-mail address and the only positive result was from office365. 
But if I tried to use that e-mail address on o365, it allowed me to create an account.
Then I check the holehe github reference and it is written there that o365 = others.
What does actually mean if the holehe alerts that an e-mail address is used on o365?

Thanks!

**Comment by megadose** [comment]
The module allows you to see if an e-mail address is valid in Office365.
For more information https://github.com/Raikia/UhOh365
