### ISSUE TITLE
implémentation vérification marmiton.com

### ISSUE THREAD

**Issue by darcosion** [megadose/holehe#55]
Actuellement, il existe une interface de reset de compte marmiton ici : ``

On peut faire un appel curl pour la réinitialisation sans CSRF, c'est limite la fête : 
```
curl 'https://www.marmiton.org/reloaded/users/forgotten-password' 'Referer: https://www.marmiton.org/reloaded/users/forgotten-password' -H 'Content-Type: application/x-www-form-urlencoded'  --data-raw 'destUrl=&email=darcosion@ibm.com&personalKey=192988092&pseudo='
```

En cas de non existence du mail, cela renvoie la même page avec un popup visuel disant : 
` Il n'existe aucun utilisateur à partir des informations fournies `
En cas d'existence, cela renvoie sur la même URL avec dans la page ceci : 
```
 Vous allez recevoir un email avec un lien de régénération de votre mot de passe

Attention : votre antispam pourrait bloquer cet e-mail.
Pour éviter cela, ajoutez info@account.marmiton.org à votre liste de contacts puis demandez un nouvel e-mail.
Pensez aussi à vérifier dans le dossier Spam de votre boite mail.
```

**Comment by darcosion** [comment]
Attention, je pense que c'est de l'actif puisque cela va envoyer un mail pour l'email vérifié.

**Comment by megadose** [comment]
The target is alerted
