### ISSUE TITLE
Ebay module issue : 'frequent_rate_limit': True, 'rateLimit: True'

### ISSUE THREAD

**Issue by brahim-janob** [megadose/holehe#57]
_Hello,_ 
I am new  to using _httpx_ , I have been trying to use the e-bay module but it wouldn't work because I keep getting this result:
**[{'name': 'ebay', 'domain': 'ebay.com', 'method': 'login', 'frequent_rate_limit': True, 'rateLimit': True, 'exists': False, 'emailrecovery': None, 'phoneNumber': None, 'others': None}]**

I tried to change the headers and the IP for every test but no luck.

If someone could fix it, that would be cool to learn from it
_thank you !_

**Comment by megadose** [comment]
it's normal ebay ban almost all ip but sometimes the module works
