### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by ddonnieddark0** [megadose/holehe#6]
Hi, i get this error when i try to execute..need help!

 15%|███████████████████▊                                                                                                             | 2/13 [00:07<00:38,  3.51s/it]
Traceback (most recent call last):
  File "holehe.py", line 13, in <module>
    infos.append({str(website).split(" ")[1].split(" ")[0]:website(args.email)})
  File "/root/Desktop/holehe/holehe/core.py", line 82, in apple
    sstt=response.text.split('sstt: encodeURIComponent("')[1].split('"')[0]
IndexError: list index out of range

**Comment by megadose** [comment]
You need to install the last version of holehe
```pip3 install holehe==1.51```
and then you will have access to the holehe command for more information read the README
