### ISSUE TITLE
containerize the cli using docker

### ISSUE THREAD

**Issue by CSalih** [megadose/holehe#73]
First of all thank you for this fantastic tool  :tada: 

**Is your feature request related to a problem? Please describe.**
Some users may not have python installed or they want to use the tool within a Container.

**Describe the solution you'd like**
* We can build a Image using a simple Dockerfile
* We can built it with [Buildpack](https://buildpacks.io/) or [Packer](https://www.packer.io/)

**Describe alternatives you've considered**
Alternative not need we can install the cli via `pip` or `py`

If you want I would provide a solution, I would be happy to contribute.

**Comment by bolshoytoster** [comment]
> Some users may not have python installed

I feel like most people who have docker and know how to use it probably also have python installed.

**Comment by megadose** [comment]
> First of all thank you for this fantastic tool tada
> 
> **Is your feature request related to a problem? Please describe.** Some users may not have python installed or they want to use the tool within a Container.
> 
> **Describe the solution you'd like**
> 
>     * We can build a Image using a simple Dockerfile
> 
>     * We can built it with [Buildpack](https://buildpacks.io/) or [Packer](https://www.packer.io/)
> 
> 
> **Describe alternatives you've considered** Alternative not need we can install the cli via `pip` or `py`
> 
> If you want I would provide a solution, I would be happy to contribute.

Well, feel free to make a pull request 👍🏼
