### ISSUE TITLE
Do not use BaseException

### ISSUE THREAD

**Issue by guyskk** [megadose/holehe#78]
**Describe the bug**

Hi, I see many code catch BaseException instead of Exception, which will cause KeyboardInterrupt and trio task timeout/cancel not work. Is there any reason to use BaseException, how about change them to Exception?

**To Reproduce**
https://github.com/megadose/holehe/search?q=BaseException

And when running holehe, the `ctrl + C` may not able to cancel the execution.

**Expected behavior**
Expect not use BaseException, and KeyboardInterrupt, trio task timeout/cancel works normally.

**Screenshots**
NA

**Additional context**
I'm glad to submit PR to fix it.

**Comment by megadose** [comment]
All right, well, feel free to push a pull request
