### ISSUE TITLE
Usage of equality operators of 'args' with None causes errors in argparse

### ISSUE THREAD

**Issue by cr4wler** [megadose/holehe#86]
https://github.com/megadose/holehe/blob/aba985792859a10466b39339c7d69bc5ea93590a/holehe/core.py#L58

This line produces errors in argparse under certain circumstances.

Replacing the '!=' operator with 'is not' fixes these issues.
Replacing argparse altogether would fix these issues and remove a dependency.

**Comment by megadose** [comment]
https://github.com/megadose/holehe/commit/7c2bde21638032a44a43ce1762fc66466e1282a7
