### ISSUE TITLE
[FEATURE REQUEST] Proxy

### ISSUE THREAD

**Issue by LucBerge** [megadose/holehe#98]
**Is your feature request related to a problem? Please describe.**
When running the script multiple time, we can have limitations on given websites.

**Describe the solution you'd like**
An option to use a proxy would be a solution.

**Additional context**
Add the option `-proxy ip:port` to use a proxy for all the requests.

**Comment by JustCallMeSimon26** [comment]
if ever added make it a proxy **list** instead.
